name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${increment}"
      # Para poder hacer referencia a este step y poder sacar sus outputs
      id: version

    - name: Docker Hub login
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
        echo "Fin del login"
    

    - name: Build Docker image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        docker build . --file Dockerfile --tag luisefarfan/docker-graphql:$NEW_VERSION
        docker build . --file Dockerfile --tag luisefarfan/docker-graphql:latest

    - name: Push Docker image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        docker push luisefarfan/docker-graphql:$NEW_VERSION
        docker push luisefarfan/docker-graphql:latest
