name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Docker Hub login
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
        echo "Fin del login"

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag luisefarfan/docker-graphql:0.0.1

    - name: Push Docker image
      run: docker push luisefarfan/docker-graphql:0.0.1
